#!/usr/bin/env bash
# -----------------------------------------------------------------
# Team Setup Script
#
# Run this once when setting up the project on a new machine.
# It creates your local .env file and fills in the values
# your admin gives you.
#
# Usage:  ./setup.sh
# -----------------------------------------------------------------

set -euo pipefail

ENV_FILE=".env"

echo ""
echo "=================================="
echo "  Distl AI Workflows — Setup"
echo "=================================="
echo ""

# Check if .env already exists
if [ -f "$ENV_FILE" ]; then
    echo "A .env file already exists."
    read -rp "Do you want to overwrite it? (y/N): " overwrite
    if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
        echo "Setup cancelled. Your existing .env was not changed."
        exit 0
    fi
    echo ""
fi

echo "Your admin should have given you the following values."
echo "Paste each one when prompted (secrets won't be visible as you type)."
echo ""

# Collect values
read -rp "MCP Server URL (from your admin): " mcp_url
echo ""
read -rsp "MCP API Key (from your admin): " mcp_key
echo ""
read -rsp "OpenAI API Key (your own, or leave blank): " openai_key
echo ""
read -rsp "Google API Key (your own, or leave blank): " google_key
echo ""

# Write .env (use quoted heredoc to prevent shell expansion of $ and backticks)
cat > "$ENV_FILE" <<'ENVEOF'
# Auto-generated by setup.sh — do not commit this file

ENVEOF

# Append each value safely (printf %s avoids interpreting special chars)
printf 'OPENAI_API_KEY=%s\n' "$openai_key" >> "$ENV_FILE"
printf 'GOOGLE_API_KEY=%s\n' "$google_key" >> "$ENV_FILE"
printf '\n# MCP Server (managed by admin)\n' >> "$ENV_FILE"
printf 'DISTL_MCP_SERVER_URL=%s\n' "$mcp_url" >> "$ENV_FILE"
printf 'DISTL_MCP_API_KEY=%s\n' "$mcp_key" >> "$ENV_FILE"

# Restrict .env to owner-only access
chmod 600 "$ENV_FILE"

echo ""
echo "Done! Your .env file has been created."
echo ""
echo "This file is in .gitignore so it will never be uploaded to GitHub."
echo "You're all set — start using Claude Code."
echo ""
